//
// RateList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RateList: Codable, JSONEncodable, Hashable {

    public var date: Date?
    public var base: String?
    public var rates: RateListRates?

    public init(date: Date? = nil, base: String? = nil, rates: RateListRates? = nil) {
        self.date = date
        self.base = base
        self.rates = rates
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case date
        case base
        case rates
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(date, forKey: .date)
        try container.encodeIfPresent(base, forKey: .base)
        try container.encodeIfPresent(rates, forKey: .rates)
    }
}

